# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#title: Your awesome title
email: godilman@outlook.com
description: "Deneyimli bir yazılım geliştirici olarak 
PHP, JS, MySQL, PostgreSQL, Oracle, NodeJS, Python, SAP ve ABAP konularında uzmanlaştım. 
Web sitemde bu teknolojiler hakkında bilgileri, deneyimlerimi ve 
ipuçlarını paylaşan blog yazılarına ulaşabilir, sevdiğim web sitelerini 
yer imlerimde bulabilir ve profesyonel özgeçmişimi inceleyebilirsiniz.
As an experienced software developer, I specialize in PHP, JS, MySQL, PostgreSQL, Oracle, 
NodeJS, Python, SAP, and ABAP. On my website, you can find blog posts sharing insights, 
experiences, and tips on these technologies, discover my favorite web bookmarks, 
and review my professional CV."
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
    - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Site settings
title: "gokhan.dev"
bye_message: "Thx!"
baseurl: "/"
url: "https://gokhan.dev"
disqus: godilman

# Header settings
nick: "godilman"
mail:
    domain: "outlook"
    ext: "com"
source_code:
    server: "github.com"
    nick: "godilman"

# Build settings
markdown: kramdown
permalink: /:categories/:title/